name: test
on: push    

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: dist
        key: my-dist-${{ github.run_number }}
    - run: |
       ls -R
       cat dist/hello.txt
    - run: |
        mkdir -p dist
        echo "hello world $RANDOM" > dist/hello.txt
    - run: |
        ls -R
        cat dist/hello.txt

  download:
    name: download
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - uses: actions/checkout@v2
    - run: |
       ls -R
       cat dist/hello.txt
    - uses: actions/cache@v2
      id: cache
      with:
        path: dist
        key: my-dist-${{ github.run_number }}
    - if: steps.cache.outputs.cache-hit != 'true'
      run: exit 1
    - run: |
       ls -R
       cat dist/hello.txt
