name: test
on: push    

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - run: |
        mkdir -p dist
        echo "hello world" > dist/hello.text
    - run: ls -R
    - uses: actions/cache@v2
      with:
        path: dist
        key: my-dist

  download:
    name: download
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - uses: actions/cache@v2
      id: cache
      with:
        path: dist
        key: my-dist
    - if: steps.cache.outputs.cache-hit != 'true'
      run: exit 1
    - run: ls -R
