name: test
on: push    

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - run: |
        mkdir -p dist
        echo "hello world" > dist/hello.text
    - run: ls -R
    - uses: actions/upload-artifact@v2
      with:
        retention-days: 1
        name: my-artifact
        path: dist

  download:
    name: download
    runs-on: ubuntu-latest
    needs: upload
    steps:
    - uses: actions/checkout@v2
    - run: ls -R
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: dist
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: my-artifact        
    - run: ls -R
